package-lock.json
package.json
src/App.css
src/App.js
src/components/favourites.js
src/components/groupmanagement.js
src/components/groups.js
src/components/login.js
src/components/logout.js
src/components/main.js
src/components/movies.js
src/components/nav.js
src/components/profile.js
src/components/reviews.js
src/components/teathers.js
src/index.js

Käyttöliittymän alustus on valmis. Bon apetit

Käyttöliittymän alustus valmis. Pöytä on katettu

---

src/App.css
src/App.js
src/components/main.js
src/components/movies.js
src/components/nav.js

Ulkoasu tehty valmiiksi. Värit laitettu, napit muokattu siistiksi. Discordiin voi laittaa kommenttia jos ei väri miellytä kaikkia.

ulkoasun muokkaus valmis

---

src/App.css

navigation bar nappien koot muokattu.

navigation bar nappien koot muokattu

---

.vscode/settings.json
src/App.css
src/components/groups.js
src/components/main.js

Groups välilehdeltä näkee nyt ryhmät

Groups välilehdeltä näkee nyt ryhmät

---

src/App.css
src/components/login.js
src/components/register.js

Kirjautumisen varmennus tehty, onnistuneelle kirjautumiselle palautetaan jsonwebtoken

Rekisteröinnin tarkistukset tehty. 

---

src/components/teathers.js

Tein nyt teatterit sivun niin että dropdownista valitaan teatteri jonka jälkeen näytetään elokuvat ja niiden esitysajat. Muokkaan tätä vielä.

teatterit sivun alustava malli

---

src/App.css
src/App.js
src/components/search.js

Elokuvien haku TMDB:stä

---

package-lock.json
src/App.css
src/App.js
src/components/login.js
src/components/logout.js
src/components/nav.js

napit seuraa kirjautumista, logout toiminnallisuus tehty

napit seuraa kirjautumista, logout toiminnallisuus tehty

---

src/App.css
src/components/login.js
src/components/main.js
src/components/register.js

Kirjaudu sisään ja rekisteröinnin sivuston css muotoilut tehty. Kirjaudu sisään nappi vie nyt main ruutuun onnistuneen kirjautumisen jälkeen.

Muotoilut ja navigoinnit tehty

---

src/components/profile.js
src/components/search.js

Käyttäjä voi poistaa oman tilinsä profiilit sivulta olevasta poista käyttäjätili napista. 
Samalla poistuu kaikki käyttäjän data.

Käyttäjä voi poistaa oman tilinsä profiilit sivulta

---

package-lock.json
package.json
src/App.css
src/components/groupmanagement.js
src/components/profile.js

Profiilin hallinnan ja Ryhmine luonnin CSS muotoilut

Profiilin hallinnan ja Ryhmine luonnin CSS muotoilut

---

src/App.css
src/components/profile.js

Ryhmät välilehti ulkoasu

---

src/App.css

Group management välilehden ulkoasu

Group management välilehden ulkoasu

---

src/App.css

Ryhmän oman sivun muotoilut

---

src/App.css

Teatteri sivun muotoilu

---

src/App.css
src/components/search.js

Search väilehden muotoilu

---

src/App.css
src/App.js
src/components/main.js
src/components/nav.js

- Login/ Register skaalautuvuus
- search bar poistettu etusivulta
- Elokuvat nappi seuraa nyt /search tiedostoon
- Ryhmät välilehden skaalautuvuus
- profiilin hallinnan skaalautuvuus
- Ryhmien hallinnan skaalautuvuus

Paljon tyylimuutoksia

---

src/App.css
src/components/main.js
src/components/nav.js

Ulkoasun ja sakaalautuvuuden muokkausta

Ulkoasun ja sakaalautuvuuden muokkausta

---

src/components/nav.js

Elokuvat Nappi Seuraa Search.js tiedostoon

Elokuvat Nappi Seuraa Search.js tiedostoon

---

src/App.css
src/components/groupmanagement.js

Ryhmään hyväksymis pyynnon CSS muotoilut

Ryhmään hyväksymis pyynnon CSS muotoilut

---

src/App.css

Etusivun mainosten muokkaus

---

src/App.css
src/components/search.js

Elokuvat sivun napit ja arvostelut lomakkeen CSS

Elokuvat sivun napit ja arvostelut lomakkeen CSS

---

src/App.css
src/components/favourites.js
src/components/reviews.js

Viimeisiä CSS muutoksia

---

src/App.css

Elokuva arvostelut skaalautuvat nyt

Elokuva arvostelut skaalautuvat nyt

---

src/App.css

Register Sivun CSS

---

src/App.css
src/components/movies.js

CSS siivous ja jaettu suosikit sivu

CSS siivous ja jaettu suosikit sivu
